home:
    path: /
    defaults: { _controller: AppBundle:Page:home }
    methods: [GET]

order:
    path: /order
    defaults: { _controller: AppBundle:Page:order }
    methods: [GET]

account_create:
    path: /account/create
    defaults: { _controller: AppBundle:Security:create }
    methods: [POST]

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }
    methods: [GET, POST]

logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout }
    methods: [GET]

check_unique_username:
    path: /check/username
    defaults: { _controller: AppBundle:Security:checkAjaxUniqueUsername }
    methods: [GET]

get_basket_messages:
    path: /basket/messages
    defaults: { _controller: AppBundle:BasketMessage:getBasketMessage }
    methods: [GET]

get_pizza:
    path: /pizza/{id}
    defaults: { _controller: AppBundle:Pizza:getPizza }
    methods: [POST]

get_pizzas:
    path: /pizzas
    defaults: { _controller: AppBundle:Pizza:getPizzas }
    methods: [GET]

add_favorite_pizza:
    path: /user/add/pizza/{id}
    defaults: { _controller: AppBundle:Pizza:addFavorite }
    methods: [GET, POST]

remove_favorite_pizza:
    path: /user/remove/pizza/{id}
    defaults: { _controller: AppBundle:Pizza:removeFavorite }
    methods: [GET, POST]

get_username:
    path: /username
    defaults: { _controller: AppBundle:User:getUsername }

get_order_reference:
    path: /order/reference
    defaults: { _controller: AppBundle:Order:getOrderReference }

group_list:
    path: /groups
    defaults: { _controller: AppBundle:Page:groups }
    methods: [GET]

get_groups:
    path: /get/groups
    defaults: { _controller: AppBundle:Group:getGroups }
    methods: [GET]

user_add_group:
    path: /user/add/group/{id}
    defaults: { _controller: AppBundle:Group:addGroup }
    methods: [GET, POST]

user_remove_group:
    path: /user/remove/group/{id}
    defaults: { _controller: AppBundle:Group:removeGroup }
    methods: [GET, POST]