home:
    path: /
    defaults: { _controller: AppBundle:Page:home }
    methods: [GET]

order:
    path: /order
    defaults: { _controller: AppBundle:Page:order }
    methods: [GET]

create_account:
    path: /account/create
    defaults: { _controller: AppBundle:Security:create }
    methods: [GET]

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }
    methods: [GET, POST]

logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout }
    methods: [GET]
