services:
    mardizza.pizza_service:
        class: AppBundle\Service\PizzaService
        arguments: [ '@doctrine.orm.entity_manager', '@request_stack', '@security.token_storage' ]

    mardizza.order_service:
        class: AppBundle\Service\OrderService
        arguments: [ '@doctrine.orm.entity_manager', '@router', '@mardizza.order' ]

    mardizza.message_service:
        class: AppBundle\Service\BasketMessageService
        arguments: [ '@doctrine.orm.entity_manager' ]

    mardizza.group_service:
        class: AppBundle\Service\GroupService
        arguments: [ '@doctrine.orm.entity_manager', '@security.token_storage' ]

    mardizza.order:
        class: AppBundle\Entity\Order

    mardizza.user:
        class: AppBundle\Entity\User
        arguments: [ '@doctrine.orm.entity_manager' ]

    mardizza.group:
        class: AppBundle\Entity\Group
        arguments: [ '@mardizza.group_service' ]

    mardizza.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app_extension.twig_extension:
        class: AppBundle\Twig\Extension\AppExtension
        public: false
        arguments: [ '@security.token_storage' ]
        tags:
            - { name: twig.extension }

    mardizza.validation_service:
        class: AppBundle\Service\ValidationService
