services:
    mardizza.pizza_service:
        class: AppBundle\Service\PizzaService
        arguments: [ '@doctrine.orm.entity_manager', '@assets.context', '@security.token_storage' ]

    mardizza.order_service:
        class: AppBundle\Service\OrderService
        arguments: [ '@doctrine.orm.entity_manager', '@router', '@mardizza.order' ]

    mardizza.order:
        class: AppBundle\Entity\Order

    mardizza.user:
        class: AppBundle\Entity\User

    mardizza.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    mardizza.message_service:
        class: AppBundle\Service\BasketMessageService
        arguments: [ '@doctrine.orm.entity_manager' ]