services:
    mardizza.pizza:
        class: AppBundle\Service\PizzaService
        arguments: [ '@doctrine.orm.entity_manager' ]

    mardizza.order:
        class: AppBundle\Entity\Order

    mardizza.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
